# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nexmo_id', models.CharField(max_length=16, unique=True)),
                ('to', models.CharField(max_length=12)),
                ('msisdn', models.CharField(max_length=12, verbose_name='sent from')),
                ('text', models.CharField(max_length=140)),
                ('received', models.DateTimeField()),
            ],
        ),
    ]
