# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 23:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_auto_20161008_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='recorded',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
