# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_auto_20161025_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
