# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-14 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_reading_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metric',
            name='x_axis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metric',
            name='y_axis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
