# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-09 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0006_axis_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reading',
            options={'ordering': ['-recorded']},
        ),
        migrations.AlterField(
            model_name='reading',
            name='recorded',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
